// <auto-generated />
namespace ClassCoustmer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cilidindu20191212 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cilidindu20191212));
        
        string IMigrationMetadata.Id
        {
            get { return "201912121407086_cilidindu20191212"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
